# This is a basic workflow to help you get started with Actions

name: Deploy Trapi Updates To Digital Ocean

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # Stop the existing app named api
      - name : Stop Current App  
        run: | 
          pm2 stop api

      # Fetch latest version of main 
      - name: Fetch Updates From Github and pull changes into main
        uses: actions/checkout@v2

      # Use yarn to install files
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # install dependencies
      - name: Install Dependencies
        run: yarn install 

      # Restart the existing app named api
      - name : Restart Current App  
        run: | 
          pm2 restart api

      # run build
      - name: run build
        run: |
        yarn run build
      
      # pm2 restart app
      - name: restart app
      run: | 
      pm2 restart api