# This is a basic workflow to help you get started with Actions

name: Deploy Trapi Updates To Digital Ocean

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # stop current app
      - name: stop current app
        run: pm2 del api

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        run : |
          git fetch
          git pull origin main
          
      - name: install dependencies
        run : yarn install

      - name: buld app
        run: yarn run build

      - name: install pg
        run: yarn add pg
      
      - name: restart app
        run: pm2 start npm --name api -- run start

      - name: syncronize process list 
        run: pm2 save


